### ISSUE TITLE
DatabaseError: Permission denied

### ISSUE THREAD

**Issue by pj9039** [Crazywater/knuffimap#1]
i try to run with virture device.
but 
`I/DynamiteModule( 7568): Selected local version of com.google.android.gms.flags
W/SyncTree( 7568): Listen at /user/fake/exercise failed: DatabaseError: Permission denied
E/flutter ( 7568): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseError(-3, Permission denied, )`
message was appeared
i made firestore with test mode and also google-services.json file in andriod/app folder.
how can i fix it?

**Comment by Crazywater** [comment]
Hi!
It looks like you're using a real Firebase database with some kind of fake login like this one: https://github.com/Crazywater/knuffiworkout/blob/master/lib/src/login/fake.dart

You need to actually use the real Firebase login that provides the Firebase User ID or the `in_memory` storage for tests.

Let me know if I can help with anything else.
